name: CADDM
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.8
  - torchvision==0.18.1
  - pytorch-cuda=11.8
  - pytorch==2.3.1
  - torchaudio==2.3.1
  - dlib

